### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Devinsuit** [vhf/free-programming-books#2234]
free-programming-books-pl.md

- [ ] 500 Can't connect to svnbook.opensys.pl:80 http://svnbook.opensys.pl
- [x] 500 Can't connect to stallman.helion.pl:80 http://stallman.helion.pl
- [x] 500 Can't connect to python.edu.pl:80 http://python.edu.pl/byteofpython/index.html

javascript-frameworks-resources.md

- [x] 404 Not Found http://tech.pro/tutorial/1562/knockoutjs-lesson-1-introduction
- [x] 404 Not Found http://tech.pro/tutorial/1563/knockoutjs-lesson-2-initialising-the-application
- [x] 404 Not Found http://tech.pro/tutorial/1564/knockoutjs-lesson-3-adding-a-viewmodel
- [x] 404 Not Found http://tech.pro/tutorial/1565/knockoutjs-lesson-4-basic-bindings
- [x] 404 Not Found http://tech.pro/tutorial/1566/knockoutjs-lesson-5-observable-arrays
- [x] 404 Not Found http://tech.pro/tutorial/1567/knockoutjs-lesson-6-the-foreach-binding
- [x] 404 Not Found http://tech.pro/tutorial/1568/knockoutjs-lesson-7-the-event-binding
- [x] 404 Not Found http://tech.pro/tutorial/1569/knockoutjs-lesson-8-the-click-binding
- [x] 404 Not Found http://tech.pro/tutorial/1570/knockoutjs-lesson-9-custom-bindings
- [x] 404 Not Found http://tech.pro/tutorial/1571/knockoutjs-lesson-10-computed-observables
- [x] 404 Not Found http://tech.pro/tutorial/1572/knockoutjs-lesson-11-the-visible-binding
- [x] 404 Not Found http://tech.pro/tutorial/1573/knockoutjs-lesson-12-the-value-binding
- [x] 404 Not Found http://tech.pro/tutorial/1574/knockoutjs-lesson-13-additional-knockout-features
- [x] 404 Not Found http://tech.pro/tutorial/1575/knockoutjs-lesson-14-adding-a-lightbox
- [x] 500 Can't connect to ghost.stevenisekimart.in:80 http://ghost.stevenisekimart.in/react-js-tutorial-creating-components

free-programming-books-ja.md

- [ ] 404 Not Found http://jubat.us/ja/aboutus.html
- [ ] 500 Can't connect to lagendra.s.kanazawa-u.ac.jp:80 http://lagendra.s.kanazawa-u.ac.jp/ogurisu/manuals/awk/intro/index.html
- [x] 500 Can't connect to www.ymotongpoo.com:80 http://www.ymotongpoo.com/works/lyse-ja/
- [x] 404 Not Found https://github.com/hatena/Hatena-Textbook/blob/master/javascript-event-driven.md
- [x] 500 Can't connect to ja.d3js.info:80 http://ja.d3js.info/alignedleft/tutorials/d3/
- [x] 404 Not Found http://gst.plasticheart.info/tutorial-c84.html
- [x] 404 Not Found http://homepage3.nifty.com/kaku-chan/tcl_tk/

free-programming-books.md

- [x] 404 Not Found http://www.flashbulbinteraction.com/WTS.html **Issue** #2192
- [x] 404 Not Found http://staff.ppu.edu/dkhalid/O'Reilly%20-%20C++%20Cookbook%20%282007%29.pdf  **Issue** #2233
- [ ] 500 Can't connect to fly.srk.fer.hr:80 http://fly.srk.fer.hr/~unreal/theredbook/ **Issue** #2195 
- [ ] 500 Internal Server Error http://dotnetslackers.com/projects/Data-Structures-And-Algorithms/
- [ ] 404 Not Found http://home.iitk.ac.in/~arlal/book/nptel/pdf/book_linear.pdf
- [x] 500 Can't connect to www.math.byu.edu:443 https://www.math.byu.edu/klkuttle/linearalgebra.pdf
- [x] 404 Not Found http://learncodethehardway.org/cli/book/
- [x] 404 Not Found https://en.wikibooks.org/wiki/Category%3ABASIC_programming_language
- [x] 500 Can't connect to howtogambas.org:80 http://howtogambas.org/index.php?page=cedi
- [ ] 500 read timeout http://www.brpreiss.com/books/opus6/
- [x] 404 Not Found https://en.wikibooks.org/wiki/Category%3AFortran_programming_language
- [x] 404 Not Found http://haskell.cs.yale.edu/?post_type=publication&p=112
- [x] 404 Not Found https://www.gitbook.com/book/openfl/openfl-documentation/details
- [x] 500 Can't connect to www.brpreiss.com:80 http://www.brpreiss.com/books/opus5/html/page9.html
- [x] 404 Not Found http://www.xml.com/ldd/chapter/book/index.html
- [ ] 404 Not Found https://psg.com/~dlamkins/sl/
- [ ] 404 Not Found http://www2.cs.uh.edu/~estrabd/openmp-combined.pdf
- [ ] 500 Status read failed: Connection reset by peer http://wiki.pcbsd.org/index.php/PC-BSD%C2%AE_Users_Handbook
- [ ] 500 Can't connect to www.masonbook.com:80 http://www.masonbook.com/book/
- [x] 500 Can't connect to modperlbook.org:80 http://modperlbook.org
- [ ] 500 read timeout http://www.brpreiss.com/books/opus7/html/book.html
- [ ] 404 Not Found http://kivy.org/docs/pdf/Kivy-latest.pdf
- [ ] 500 Status read failed: Connection reset by peer http://stwww.weizmann.ac.il/g-cs/scratch/scratch_en.html

free-programming-books-zh.md

- [x] 500 Can't connect to docs.neo4j.org.cn:80 http://docs.neo4j.org.cn
- [x] 404 Not Found http://www.kerneltravel.net/kernel-book/%E6%B7%B1%E5%85%A5%E5%88%86%E6%9E%90Linux%E5%86%85%E6%A0%B8%E6%BA%90%E7%A0%81.html
- [ ] 404 Not Found http://vbird.dic.ksu.edu.tw/linux_basic/linux_basic.php
- [ ] 404 Not Found http://vbird.dic.ksu.edu.tw/linux_server/
- [ ] 500 Can't connect to bucunzai.net:80 http://bucunzai.net/hginit/
- [ ] 500 Can't connect to bbs.konotes.org:80 http://bbs.konotes.org/workdoc/puppet-27/
- [ ] 404 Not Found http://leanote.com/blog/post/561658f938f41126b2000298?hmsr=toutiao.io&utm_medium=toutiao.io&utm_source=toutiao.io
- [x] 404 Not Found http://www.hellogcc.org/effective_go.html
- [ ] 500 Can't connect to go-tour-zh.appsp0t.com:80 http://go-tour-zh.appsp0t.com
- [x] 400 Bad Request https://github.com/karlseguin/the-little-go-book)%E3
- [ ] 409 Conflict http://learnyoua.haskell.sg
- [ ] 500 Can't connect to mweb.baidu.com:80 http://mweb.baidu.com/zeptoapi/
- [x] 404 Not Found https://www.gitbook.com/book/0532/nodejs/details)%EF
- [ ] 404 Not Found http://www.cbi.pku.edu.cn/chinese/documents/perl/index.htm
- [x] 404 Not Found http://www.biosino.org/R/R-doc/files/R4beg_cn_2.0.pdf

free-courses-en.md

- [x] 500 Internal Server Error https://rubymonk.com

problem-sets-competitive-programming.md

- [ ] 500 Can't connect to www.codeforces.com:443 https://www.codeforces.com/problemset

free-programming-books-pt_BR.md

- [ ] 404 Not Found http://www.filoczar.com.br/sistemas_operacionais/linux/cpppara_linux.pdf

free-programming-books-tr.md

- [x] 404 Not Found http://yzgrafik.ege.edu.tr/~tekrei/dersler/bbgd_p/BBGD_PIO.pdf

free-programming-books-es.md

- [ ] 500 Can't connect to www.wolnm.org:80 http://www.wolnm.org/apa/articulos/Ingenieria_Software.pdf
- [x] 500 Can't connect to www.openflbook.com:80 http://www.openflbook.com
- [x] 500 Can't connect to www.libropctr.com:80 http://www.libropctr.com
- [x] 404 Not Found http://ignaciolasalvia.com/material/prog1_2013/GuiaJavaparaDocentes2012.pdf
- [x] 500 Status read failed: Connection reset by peer http://www6.uniovi.es/perl/tutor/
- [ ] 500 Can't connect to arawako.com:80 http://arawako.com/wp-content/uploads/2010/03/thinkCSpy.es_.pdf

free-programming-books-ko.md

- [x] 404 Not Found http://eriny.net/p/perl

free-podcasts-screencasts-en.md

- [x] 500 Can't connect to showmedo.com:80 http://showmedo.com/videotutorials/javascript
- [x] 500 Can't connect to showmedo.com:80 http://showmedo.com/videotutorials/python
- [x] 500 Can't connect to showmedo.com:80 http://showmedo.com/videotutorials/ruby

free-programming-interactive-tutorials-en.md

- [x] 503 Service Unavailable http://www.hackety.com
- [x] 500 Internal Server Error https://rubymonk.com
- [x] 503 Service Unavailable http://www.scala-tour.com

javascript-frameworks-resources-pt_BR.md

- [x] 404 Not Found http://vuejs-br.github.io/vuejs.org/
- [x] 404 Not Found http://www.vedcasts.com.br/series/vuejs

free-programming-books-ru.md

- [x] 500 Can't connect to lisper.ru:80 http://lisper.ru/pcl/
- [ ] 404 Not Found https://gordon-f.github.io/rust-by-example-ru/

free-programming-books-fr.md

- [ ] 404 Not Found http://pdp.microjoe.org/tutoriels/280/dropbox-a-des-fuites/
- [x] 500 read timeout http://sagebook.gforge.inria.fr

**Comment by vhf** [comment]
Thanks! 💯
